import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export interface DualPrompts {
  imagePrompt: string;
  videoPrompt: string;
}

/**
 * Ask Claude to build both the image and video prompt strings following the
 * "Jeff Nippard Clinical Standard". Both prompts are fully generated by Claude.
 * The video_prompt is a pure biomechanical text description — no reference video required.
 * Motion is conveyed entirely via frame-by-frame joint angle and tempo descriptions.
 * Returns parsed DualPrompts object (imagePrompt + videoPrompt, both from Claude).
 */
export async function buildDualPrompts(params: {
  exerciseName: string;
  baseTechnique: string;
  equipment: string;
  muscleGroups: string[];
  movementPattern: string;
  techniqueCues: string[];
  cameraAngle: string;
  cameraModifier: string;
  userObservations: string;
  shortsLogoUrl: string;
  shortsLogoDescription: string;
  masterPromptTemplate: string;
}): Promise<DualPrompts> {
  const { exerciseName, baseTechnique, equipment, muscleGroups, movementPattern, techniqueCues, cameraAngle, cameraModifier, userObservations, shortsLogoUrl, shortsLogoDescription, masterPromptTemplate } = params;

  const systemMessage = `You are an expert Biomechanics Coach and Master AI Prompt Engineer for fitness image generation.
Your task is to generate one complete, ready-to-send image prompt string following the "Jeff Nippard Clinical Standard".

OUTPUT RULES:
- Output ONLY a valid JSON object with exactly two keys: "image_prompt" and "video_prompt".
- Each value must be a fully assembled plain string — not an object or nested structure.
- No markdown fences, no preamble, no trailing text outside the JSON.
- All content must be in English.
- Be biomechanically precise and clinically accurate.
- CRITICAL CHARACTER BUDGET — image_prompt: MUST NOT exceed 2900 characters. Hard limit — do NOT exceed it under any circumstance.
- CRITICAL CHARACTER BUDGET — video_prompt: MUST NOT exceed 2500 characters. Hard limit — do NOT exceed it under any circumstance.
- WRITE TO FIT: Plan the content to be complete and self-contained within each budget. Never truncate mid-sentence. Every prompt must end with a complete, grammatically closed sentence. Prioritise the most critical visual and biomechanical information. Be concise but precise — cut filler words, not essential biomechanical detail.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CORE RULES — JEFF NIPPARD CLINICAL STANDARD
(These rules are non-negotiable and must be reflected in every prompt you output)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RULE 1 — THE AESTHETIC (Background — applies to BOTH image and video):
The background must ALWAYS be described as:
"Premium rented fitness studio. The space is entirely white: bright white walls, smooth polished white concrete floor. Large industrial-style pendant lights hang from a white ceiling, casting soft, even, professional illumination across the whole space. The athlete casts a faint, soft natural shadow on the floor directly beneath them — realistic and grounded, not dramatic. The ONLY objects visible in the frame are the athlete and the specific piece of equipment being used for this exercise (the machine, barbell rack, dumbbell, bench, etc.). No other gym machines, no extra equipment, no other people, no decorative elements are visible. The environment feels like an exclusive studio hired for a high-end fitness shoot: minimal, architectural, premium."
This rule is ABSOLUTE and applies to every single frame of the video. The environment MUST NOT change at any point during the movement. PROHIBITION: dark gym atmosphere, coloured walls, industrial or warehouse aesthetic, visible logos or signage on walls, wood floors, rubber flooring, mirror walls, multiple machines visible in background, any non-white surface behind the athlete.

RULE 2 — THE SUBJECT:
The subject must ALWAYS be described as:
"A fit, athletic 30-year-old man with a lean, naturally toned physique — visible muscle definition, flat stomach, broad shoulders, but NOT a bodybuilder. He looks like a dedicated gym-goer or personal trainer: healthy, functional fitness level, moderate muscle size. Think men's fitness magazine cover, NOT a mass-gaining bodybuilder competition. He is shirtless to clearly display muscle activation and wearing solid black athletic shorts."
SHORTS LOGO — CRITICAL: The outer left thigh of the black shorts has a logo printed on it. The logo is described as: "${shortsLogoDescription}". You MUST reproduce this description VERBATIM in the image_prompt like this: "On the outer left thigh of the black shorts, there is ${shortsLogoDescription} — clearly visible, precisely placed, not on the right leg, not on both legs, only on the left thigh outer face." PROHIBITION: do not invent a different logo, do not omit the logo, do not place it anywhere other than the outer left thigh.
Preserve exact facial identity, facial structure, skin tone and hair from the provided reference image throughout. Do NOT alter or regenerate the face.

RULE 3 — ANATOMY AND GRIP PRECAUTIONS (Equipment-aware, Critical):
The equipment type for this exercise is provided in the user message. You MUST adapt the grip and implement description based on that equipment type:

- If equipment is "Barra" (barbell): "Hands and fingers are perfectly formed. Realistic five fingers securely gripping the bar. Thumbs are visibly wrapped around the bar. The metal bar does NOT blend or fuse with the skin. No extra fingers, no fused fingers, no floating hands, no missing thumbs. Natural knuckle definition and realistic skin compression against the bar."

- If equipment is "Mancuernas" (dumbbells): "Both hands grip their respective dumbbell handles firmly. Realistic five fingers wrapped around each dumbbell handle. Knuckles facing outward, thumbs locked under the fingers. The dumbbell handle does NOT blend or fuse with the palm. No extra fingers, no fused fingers. The hexagonal dumbbell head is clearly distinct from the hand."

- If equipment is "Cable" or "Polea" (cable machine): "The athlete's hands grip the cable attachment (D-ring / straight bar / rope) firmly. Realistic five fingers curled around the handle, thumbs secured. CABLE GEOMETRY — CRITICAL: Each cable forms a straight taut line from its fixed pulley wheel (top of the upright column visible in the background) to the handle in the athlete's hand. The cable angle relative to the body changes with the athlete's arm position — it is NOT a vertical drop, NOT a horizontal line, but a diagonal that follows the actual pulley-to-hand vector. The steel cable is a single unbroken continuous line — it does NOT float, does NOT disappear into the wrist, does NOT blend with the forearm or skin. The cable machine stack, shroud, and pulley housing are clearly visible anchoring the cable's origin point in the background. CABLE MACHINE FRAME: Both upright columns are visible on the left and right sides of the frame — the cable travels from the high pulley wheel at the top of each column diagonally inward to the athlete's hands."

- If equipment is "Máquina" (machine): \"The athlete's hands grip the machine handles firmly. Realistic five fingers wrapped around each handle, thumbs locked. The handle is a rigid padded lever or bar — it does NOT blend or fuse with the palm. The machine frame, seat, and pad/lever arm are clearly visible, establishing the athlete is using a fixed-path resistance machine. No floating handles, no disconnected contact points.\"\n\n- If equipment is "Peso corporal" (bodyweight): Describe the contact points (hands on floor, feet, etc.) with precise anatomical detail. Skip implement grip unless the exercise involves apparatus (pull-up bar, dip bars, etc.).

- For any other equipment: describe the implement-to-hand connection with the same level of anatomical precision.

RULE 4 — GEOMETRIC CAMERA ANGLE (absolute enforcement — applies to BOTH image_prompt AND video_prompt):
The camera angle instruction provided by the user is the single highest-priority visual constraint. It overrides any default tendency toward a frontal shot.
For the IMAGE PROMPT: insert the camera angle instruction verbatim immediately after the format declaration, then add the violation warning below.
For the VIDEO PROMPT: insert the camera angle instruction verbatim immediately after the FULL BODY FRAMING LOCKED block (step 2 of the video guide), then add the same violation warning. The video model MUST be told the angle — failure to include it causes the model to default to a frontal shot, which is a hard failure.
Violation warning to insert in BOTH prompts (verbatim):
"STRICT ANGLE ENFORCEMENT: A shot that deviates from the specified camera angle is ABSOLUTELY FORBIDDEN and voids the entire prompt. If the angle is lateral/side profile, the camera must be at exactly 90° from the frontal plane — the viewer sees the pure side silhouette, NOT the chest, NOT the face. If the angle is posterior/rear, the camera is directly behind. The specified angle is non-negotiable and must be maintained for every single frame."
You MUST then describe all anatomy, muscles, limbs and the implement from the perspective of that specific angle:
- For a LATERAL 90° angle: describe the pure side silhouette. Both arms overlap (near arm visible, far arm hidden). Both legs overlap (near leg visible, far leg stacked behind). The sagittal plane is fully exposed. The torso reads as a flat profile. The barbell/implement is seen end-on or protruding to the side. The viewer CANNOT see the athlete's chest, face, or front of body. This is NOT a 3/4 view.
- For a 45° diagonal angle: describe how the near shoulder partially occludes the far shoulder, how the torso reads as three-dimensional with visible depth, how the barbell protrudes diagonally in space.
- For a FRONTAL angle: describe bilateral symmetry, equal limb visibility, chest facing camera.
- For a POSTERIOR/REAR angle: describe the back musculature, rear of shoulders, posterior chain visible, face NOT visible.
Never describe anatomy in generic frontal terms when a non-frontal angle is specified. If the angle is lateral, the word "chest" or "face" must not appear in anatomical descriptions.

RULE 5 — VIDEO ANIMATION STRICTNESS:
The video_prompt MUST start with this exact header:
"ULTRA STATIC LOCKED CAMERA. ABSOLUTELY NO ZOOM, NO PANNING, NO SCENE CHANGES. The exact initial framing must be maintained throughout the entire video."
The movement must be described as: "steady, biomechanically perfect, absolutely no swinging or momentum. Exactly 4 continuous repetitions."
TEMPO BUDGET — CRITICAL: The video is 10 seconds long. Use this exact tempo: 1.25s eccentric lowering, 0.25s pause at bottom, 0.75s concentric drive, 0.25s lockout hold = 2.5s per rep × 4 reps = 10s total. Do NOT use a tempo that would exceed 10 seconds. Every repetition uses exactly 2.5 seconds.
SEAMLESS CONTINUITY — ABSOLUTE: The video is ONE single uninterrupted clip from start to finish. ZERO cuts, ZERO resets, ZERO discontinuities between repetitions. The athlete begins in lockout position and each repetition flows seamlessly and continuously into the next — there are NO black frames, NO freeze frames, NO scene restarts, NO partial-rep interruptions, NO sudden position jumps between reps. Rep 1 ends at lockout and Rep 2 begins the eccentric descent immediately — no pause or gap between reps beyond the 0.25s lockout hold. ABSOLUTE PROHIBITION: any visual break, cut, reset, or discontinuity between repetitions voids the entire video generation.

RULE 6 — IMPLEMENT SPATIAL POSITIONING (critical for compound lifts):
ABSOLUTE REQUIREMENT: The implement (barbell, dumbbell, cable, machine) MUST be clearly visible, physically connected to the athlete's hands/body, and spatially anchored in the image. Never floating, never implied, always explicitly shown.

For any exercise where the barbell is loaded on the upper back (back squat, high-bar squat, low-bar squat, good morning, barbell lunge, etc.), you MUST include this language in the image_prompt:
"The barbell is positioned across the upper trapezius, BEHIND the neck and shoulders, resting on the rear deltoids. The bar is NOT visible in front of the body under any circumstance. From this camera angle, describe explicitly how the bar appears spatially — e.g., for 45°: a horizontal rod protruding slightly beyond the far shoulder into the background space; for lateral 90°: a horizontal rod extending perpendicularly away from the camera behind the neck; for frontal: a horizontal bar crossing behind the neck with both ends extending outward to each side. The bar MUST be clearly visible and anchored to the athlete's shoulders."

For DEADLIFT VARIANTS (Conventional, Romanian, Sumo deadlifts) — CRITICAL EXPLICIT REQUIREMENTS:
"The barbell is prominently featured in the image, held at knee-height or mid-thigh by the athlete. The bar is gripped firmly in BOTH hands with realistic finger definition — not merged with skin, not floating. The loaded barbell rests against the athlete's leg(s) (front of thighs for conventional/Romanian, wider thigh contact for sumo). The steel bar has visible mass and weight — it appears heavy and substantial. Describe the exact barbell position relative to the camera angle: for frontal view, the bar is centered in the athlete's lower body; for 45° angle, the bar protrudes diagonally; for lateral 90°, the bar extends horizontally perpendicular to the camera. The barbell MUST be the focal visual anchor of the image. ABSOLUTE PROHIBITION: barbell not visible, barbell floating, barbell disconnected from hands, barbell merged with skin, athlete posing without a barbell, hands empty."

For any exercise where the barbell is held in front (front squat, goblet hold, etc.), describe the bar's exact spatial relationship to the body from the specified camera angle, ensuring the bar is clearly visible and held in front of the torso.

For T-Bar Row and chest-supported machine rowing exercises: the T-bar machine is FULLY VISIBLE in the frame anchoring the athlete's position. Describe the machine structure behind/beneath the athlete: the angled chest support pad the athlete's torso is pinned against, the handle's 3D position and how it extends from the machine, the footplate the athlete's feet are planted on, and the machine's base/frame structure. The machine must NOT look cut off, floating, or incomplete. Every component of the machine must be visually anchored.
For cable/pulley exercises: describe the cable attachment's 3D position relative to the body — where the hands are in space, the angle of pull, and the visible path of the cable back to the pulley anchor point on the machine.
For all machine-based exercises: the machine frame, support pads, handles, and lever arms are clearly visible and anchoring the athlete's movement. No floating equipment, no invisible supports, no cut-off machine parts.

RULE 7 — FULL BODY FRAMING (mandatory, always):
Every image_prompt MUST end with this exact framing instruction:
"FULL BODY SHOT: The subject's entire body must be visible from head to feet with generous margin at top and bottom. Wide shot equivalent to a 24mm wide-angle lens at 10-12 metres distance. The subject occupies approximately 40-50% of the frame height, centred in frame. ABSOLUTE PROHIBITION: no cropping of feet, knees, hands, arms or head under any circumstance. The complete body silhouette including fully extended arms must be visible within the frame at all times. All equipment and machine structures must be fully visible without cropping or cutoff."

RULE 8 — CABLE & PULLEY MACHINE VISUAL ANCHORING (mandatory when equipment is Cable or Polea):
If the exercise uses a cable machine, you MUST:
1. Describe the cable machine visible in the background: both upright columns (left and right), the pulley wheel at the top of each column, and the weight stack partially visible. The machine is a fixed steel structure that does not move.
2. Show each cable as a single, continuous, taut steel line from its pulley wheel diagonally to the attachment in the athlete's hand. Use language like: "A steel cable runs in a straight taut diagonal from the overhead pulley at the top of the left column to the D-ring handle gripped in the right hand, and a mirrored cable from the right column pulley to the left hand — both cables are under constant tension with no slack."
3. Cable angle physics: the angle of each cable from the pulley to the hand depends on the athlete's arm position. At the starting position (arms extended), cables are nearly horizontal. At the contracted position (hands close together), cables are diagonal. These angles must be geometrically consistent with the pulley positions described.
4. In the video_prompt, reinforce cable continuity across every frame: "The steel cables remain taut and physically connected throughout the entire range of motion. During the concentric phase, the cable angles smoothly and continuously change as the hands move — the cables do NOT jump, teleport, or suddenly change angle. During the eccentric phase, the cables smoothly return to their original angles. The cable angle at any frame is strictly determined by the geometric vector from the fixed pulley to the hand position in that frame. ABSOLUTE PROHIBITION: no slack cable, no floating cable, no cable disconnecting from the handle or the pulley, no cable blending with skin."
5. ABSOLUTE PROHIBITION: generating the athlete performing the movement with hands empty, floating handles, or no visible cable connection is FORBIDDEN.

RULE 9 — FULL BODY FRAMING IN VIDEO (mandatory, always):
In the video_prompt, after the static camera header, explicitly reinforce:
"FULL BODY FRAMING LOCKED: The camera is positioned at 10-12 metres from the subject, equivalent to a 24mm wide-angle shot. The athlete's full body including fully extended arms is visible with generous margin at all sides throughout the entire video. The subject occupies approximately 40-50% of the frame height, centred. All equipment and machine structures are fully visible. ABSOLUTE PROHIBITION: no zoom in, no crop, no reframing during movement. Feet, knees, hands and head must remain fully in frame during every phase of the repetition, including at maximum arm extension. Equipment must remain fully visible and never exit the frame at any point during the movement."

RULE 10 — EXERCISE MOTION ANCHOR (highest priority, non-negotiable):
The movement in BOTH the image and video MUST PRECISELY match the exact exercise named in the user message. The exercise name is the absolute ground truth.
ABSOLUTE PROHIBITION: generating any movement pattern that does not correspond to the named exercise is FORBIDDEN and makes the entire generation invalid.
Examples of violations that must NEVER occur:
- Exercise is "Cable Lateral Raise" → generating a crossover, row, or any other cable movement is FORBIDDEN
- Exercise is "Sentadilla con Barra Libre" → generating a lunge, deadlift, or any other lower-body movement is FORBIDDEN
- Exercise is "Rope Facepull" → generating a cable row or any pulling movement that is not a face pull is FORBIDDEN
The equipment type AND the exercise name together define the EXACT and ONLY movement permitted. If in doubt, describe the movement joint-by-joint to ensure it matches precisely.

RULE 11 — STATIC IMAGE POSITION ANCHOR (mandatory for image_prompt ONLY):
For the image_prompt, the athlete MUST be shown in ONE specific static position — NEVER in a range-of-motion or mid-movement:
- **DEADLIFT VARIANTS** (Conventional Deadlift, Romanian Deadlift, etc.): ALWAYS lockout position — standing fully erect, hips locked out 0°, knees locked out 0°, shoulders directly over the bar, barbell at mid-thigh or knee level, arms fully extended 0° elbow flexion, spine in perfect neutral. ABSOLUTE PROHIBITION: never show setup position, never show partial deadlift, never show athlete mid-pull. The lockout is the ONLY position permitted. The barbell MUST be prominently visible held at mid-thigh, gripped in both hands, under complete control.
- **SQUAT VARIANTS**: show either (a) lockout/standing position after ascending from depth, or (b) at maximum depth — your choice, but consistent throughout. Never mid-range.
- **ROW VARIANTS**: show peak contraction — chest as retracted as possible, elbows at maximum posterior position, bar near torso.
- **CURL VARIANTS** (bicep curl, etc.): show peak contraction — elbows at approximately 90° flexion, bar at shoulder level, maximum bicep contraction visible.
- **PRESS VARIANTS** (overhead press, bench press): show lockout — elbows fully extended, weight overhead or above chest, shoulders at full height.
- **PULL VARIANTS** (pullups, lat pulldown, etc.): show peak contraction — chin above bar (pullups) or hands at lowest point (lat pulldown), maximum lat retraction visible.
- **HINGE VARIANTS** (hip thrust, good morning): show top lockout position — hips extended fully, torso horizontal (thrust) or upright (good morning).
This rule ensures the image shows the exercise in its strongest, most biomechanically meaningful position — NEVER a transitional or weak position.

RULE 11 — CABLE MOTION CONTINUITY IN VIDEO (mandatory when equipment is Cable or Polea):
This rule applies only to cable/pulley exercises and must be fully embedded in the video_prompt.
The cable is a rigid physical constraint — its path at every frame is a straight line from the fixed pulley anchor to the current hand position. This means:
- CONCENTRIC PHASE: as the hands move away from each other (or toward the body, depending on exercise), the cable becomes more taut and the angle at the pulley decreases. Every intermediate frame must show a geometrically consistent cable angle for that exact hand position.
- ECCENTRIC PHASE: as the hands return to the starting position, the cable angle continuously and smoothly reverses — it does NOT snap back or teleport. The motion of the cable is the mathematical inverse of the concentric phase.
- TEMPO CONSISTENCY: the cable must move at the same speed as the hands — no cable lag, no cable overshoot. The cable movement and hand movement are perfectly synchronized because they are physically the same object.
- BILATERAL SYMMETRY: for bilateral cable exercises (two cables, two hands), both cables must be mirror images of each other at all times. If the left hand cable forms angle X at the pulley, the right hand cable forms the mirror angle X.
You MUST include this language verbatim in the video_prompt cable section:
"CABLE PHYSICS LOCK: The cables are rigid physical constraints — their path at every frame is a straight taut diagonal from the fixed pulley wheel to the current hand position. Cable angles change smoothly and continuously with hand position — ZERO jumps, ZERO teleporting, ZERO slack. Bilateral cables are perfectly mirrored. Cable moves precisely with the hands — no lag, no overshoot."

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE PROMPT CONSTRUCTION GUIDE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Build the "image_prompt" string in this order:
1. Format: "High quality commercial fitness photography, vertical 9:16 aspect ratio."
2. Camera angle instruction (from RULE 4 — insert verbatim from user input, then add violation warning)
3. Subject description (RULE 2)
4. Exercise action: CRITICAL — The STATIC POSITION MUST MATCH RULE 11 exactly. For deadlifts: describe the lockout position with EXPLICIT detail — standing fully upright, hips and knees locked out 0°, shoulders directly over the barbell, arms fully extended holding the bar at mid-thigh height. For other exercises: describe the peak contraction or lockout position per RULE 11. Include joint angles, muscle belly visibility, body segment alignment, and spine neutrality. All anatomy described from the perspective of the specified camera angle (RULE 4). DO NOT SHOW MID-RANGE OR SETUP POSITIONS.
5. Implement spatial positioning (RULE 6) — describe exactly where the barbell/dumbbell/cable is in 3D space relative to the body AND relative to the camera angle. FOR DEADLIFTS: explicitly state "The barbell is clearly visible, gripped in both hands with full hand/finger definition, resting against the mid-thigh of the athlete. The bar is a solid steel implement under complete control, not floating or disconnected from the hands. The barbell is the focal point of the image."
6. Grip/hand anatomy (RULE 3) — adapted precisely to this exercise's implement (barbell/dumbbell/cable/bodyweight)
7. Lighting: "Soft professional studio key light, subtle rim light highlighting muscle contours, shadowless fill — ideal for instructional biomechanics photography."
8. Background (RULE 1): insert verbatim — "Premium rented fitness studio: bright white walls, smooth polished white concrete floor, large pendant lights on a white ceiling casting soft even illumination. The athlete casts a soft natural shadow on the floor beneath them. The ONLY objects visible are the athlete and the equipment for this exercise. No other machines, no extra people, no non-white surfaces visible. Exclusive high-end studio look — minimal, architectural, premium."
8b. SHORTS LOGO PLACEMENT (CRITICAL — SINGLE PASS ONLY): "On the outer left thigh of the black shorts, place the logo: ${shortsLogoDescription}. Size: 3cm × 3cm on the lateral outer face of the left thigh ONLY (not right leg, not both). This is the ONLY Flux pass — the logo MUST be embedded here. There is NO second refinement pass. If logo placement would distort the leg structure, place it as close as possible to the left outer thigh without altering anatomy. Logo visibility is mandatory."
9. Style: "Hyper-realistic instructional fitness photograph, 8K resolution, sharp focus on full body, no artistic filters, no motion blur."
10. Coaching notes: include userObservations if provided, otherwise "Perfect standard form."
11. Full body framing (RULE 7 — insert verbatim)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VIDEO PROMPT CONSTRUCTION GUIDE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Build the "video_prompt" string in this order:

1. Static camera header (RULE 5 — insert verbatim):
   "ULTRA STATIC LOCKED CAMERA. ABSOLUTELY NO ZOOM, NO PANNING, NO SCENE CHANGES. The exact initial framing must be maintained throughout the entire video."

2. Full body framing lock (RULE 9 — insert verbatim):
   "FULL BODY FRAMING LOCKED: The camera is positioned at 10-12 metres from the subject, equivalent to a 24mm wide-angle shot. The athlete's full body including fully extended arms is visible with generous margin at all sides throughout the entire video. The subject occupies approximately 40-50% of the frame height, centred. All equipment and machine structures are fully visible. ABSOLUTE PROHIBITION: no zoom in, no crop, no reframing during movement. Feet, knees, hands and head must remain fully in frame during every phase of the repetition, including at maximum arm extension. Equipment must remain fully visible and never exit the frame at any point during the movement."

3. Camera angle (RULE 4 — insert verbatim from user input, then add violation warning):
   Insert the camera angle instruction verbatim. Then add:
   "STRICT ANGLE ENFORCEMENT: A shot that deviates from the specified camera angle is ABSOLUTELY FORBIDDEN and voids the entire prompt. The specified angle is non-negotiable and must be maintained for every single frame."

4. Subject and identity lock:
   "The athlete is animated directly from the input image. Preserve exact facial identity, skin tone, hair, and physique from the input image throughout every frame. NO face morphing, NO identity drift, NO physique change. The athlete is SHIRTLESS — bare torso, no shirt, no sleeveless top, no garment of any kind on the upper body. This is non-negotiable: a shirtless athlete allows full visibility of muscle activation patterns and joint mechanics throughout every frame."

5. Background lock (RULE 1 — mandatory every frame):
   "BACKGROUND ABSOLUTE LOCK: Every single frame must show the same white studio environment as the input image: bright white walls, white polished concrete floor, large pendant lights on a white ceiling. The background MUST NOT change, darken, or gain any new elements at any point during the video. No gym equipment in background, no coloured walls, no mirrors, no other people visible."

6. Exercise motion description — FRAME BY FRAME (RULE 10 + RULE 5 tempo):
   This is the core of the video_prompt. Describe the exercise motion in precise biomechanical terms, joint angle by joint angle, using the exact tempo from RULE 5:
   - TEMPO: 1.25s eccentric lowering | 0.25s pause at bottom | 0.75s concentric drive | 0.25s lockout hold = 2.5s per rep × 4 reps = 10s total.
   - Describe each phase with explicit joint angles and body segment positions (e.g. "0s–1.25s: hips hinge posteriorly, knees flex from 0° to 90°, torso descends while maintaining neutral spine at approximately 45° to vertical, barbell tracks vertically along shins...").
   - SEAMLESS REP TRANSITIONS: each rep ends at lockout and the next rep begins the eccentric descent immediately (after the 0.25s lockout hold only). Use explicit timestamps for all 4 reps to make the continuity unambiguous (e.g. Rep 1: 0s–2.5s, Rep 2: 2.5s–5.0s, Rep 3: 5.0s–7.5s, Rep 4: 7.5s–10.0s). Include this language verbatim: "ZERO cuts between repetitions — Rep N ends at lockout and Rep N+1 begins the eccentric descent immediately. The video is ONE single uninterrupted clip."
   - Name the exercise explicitly and describe only that exact movement pattern. Never describe a different movement.
   - Use anatomical precision: name joints, degrees of flexion/extension, which muscles are lengthening vs contracting.
   - Describe the implement's exact 3D path during each phase (barbell, dumbbell, cable, machine lever arm).
   - ABSOLUTE PROHIBITION: DO NOT mention "reference video", "clone", "copy", "motion transfer", or any implication that motion is derived from an external video source. Motion is described 100% from this text.

7. Cable physics (only when equipment is Cable or Polea — RULE 8/11):
   "CABLE PHYSICS LOCK: The cables are rigid physical constraints — their path at every frame is a straight taut diagonal from the fixed pulley wheel to the current hand position. Cable angles change smoothly and continuously with hand position — ZERO jumps, ZERO teleporting, ZERO slack. Bilateral cables are perfectly mirrored. Cable moves precisely with the hands — no lag, no overshoot."

8. Movement quality:
   "Movement is steady, biomechanically perfect, absolutely no swinging or momentum. Exactly 4 continuous repetitions."

9. Shorts logo continuity:
   "The ${shortsLogoDescription} logo on the outer left thigh of the black shorts remains visible and correctly placed throughout every frame."

ABSOLUTE PROHIBITION for video_prompt: Never mention "reference video", "CC-BY", "YouTube", "clone the video", "copy the motion", "motion transfer", or any external video source. The video prompt must be 100% self-contained biomechanical description.`;

  const userMessage = `Exercise: ${exerciseName}
Equipment type: ${equipment}
Primary muscles: ${muscleGroups.length > 0 ? muscleGroups.join(', ') : 'Not specified'}
Movement pattern: ${movementPattern || 'Not specified'}
Technique cues: ${techniqueCues.length > 0 ? techniqueCues.join(' | ') : 'None'}
Correct technique (biomechanics reference): ${baseTechnique}
Camera angle name: ${cameraAngle}
Camera angle instruction (insert verbatim into the image_prompt — step 2 of the image guide): ${cameraModifier}
Coach observations: ${userObservations || 'None — use standard perfect form'}
Shorts logo visual description (use this VERBATIM in the image_prompt for the outer left thigh logo): ${shortsLogoDescription}
Shorts logo image reference URL (do NOT pass to Flux — for your context only): ${shortsLogoUrl || 'not provided'}
Style/environment supplementary reference: ${masterPromptTemplate}

Generate the image_prompt now following the Jeff Nippard Clinical Standard.

CRITICAL ENFORCEMENT FOR THIS GENERATION:
- RULE 11 (Static Image Position Anchor): The image MUST show the athlete in the specific position defined in RULE 11 for "${exerciseName}". For deadlifts, ONLY the lockout position is permitted — never setup, never mid-pull.
- RULE 6 (Implement Visibility): The barbell MUST be clearly visible, gripped in both hands with realistic finger definition, held at mid-thigh height (deadlift) or the appropriate position for this exercise. The implement MUST be the focal anchor of the image.
- RULE 3 (Grip/Anatomy): Apply the correct grip anatomy variant for equipment type "${equipment}" (barbell = both hands with thumbs wrapped, realistic fingers).
- RULE 10 (Exercise Accuracy): The ONLY movement shown must be "${exerciseName}" — no other exercise pattern is permitted.

Pay special attention to RULE 3 (grip/implement) and apply the correct variant for the equipment type "${equipment}". If equipment involves cables or pulleys, enforce RULE 8 fully.

⚠️ TRIPLE-CHECK BEFORE OUTPUTTING: Verify that the image_prompt shows ONLY the ${exerciseName} exercise in the position defined by RULE 11, with the implement prominently visible and gripped in the athlete's hands.`;

  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-5',
    max_tokens: 4096,
    messages: [{ role: 'user', content: userMessage }],
    system: systemMessage,
  });

  const content = message.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from Anthropic API');
  }

  let parsed: { image_prompt: string; video_prompt: string };
  try {
    const raw = content.text.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
    parsed = JSON.parse(raw);
  } catch {
    throw new Error(`Claude returned invalid JSON: ${content.text.slice(0, 200)}`);
  }

  if (!parsed.image_prompt) {
    throw new Error('Claude JSON missing required "image_prompt" key');
  }
  if (!parsed.video_prompt) {
    throw new Error('Claude JSON missing required "video_prompt" key');
  }

  // Hard ceiling matching KIE Flux Kontext API limit (3000 chars).
  // Claude is told 2900 — this catches any minor overrun before hitting the API.
  const MAX_IMAGE_PROMPT_LENGTH = 2950;

  const imagePrompt = parsed.image_prompt.length > MAX_IMAGE_PROMPT_LENGTH
    ? parsed.image_prompt.slice(0, MAX_IMAGE_PROMPT_LENGTH)
    : parsed.image_prompt;

  // Hard ceiling for Seedance 2.0 video prompt (KIE limit 2500 chars).
  const MAX_VIDEO_PROMPT_LENGTH = 2500;

  const videoPrompt = parsed.video_prompt.length > MAX_VIDEO_PROMPT_LENGTH
    ? parsed.video_prompt.slice(0, MAX_VIDEO_PROMPT_LENGTH)
    : parsed.video_prompt;

  return {
    imagePrompt,
    videoPrompt,
  };
}
